name: Update dependencies (weekly)
on:
  schedule:
    - cron:  '0 4 * * 1'
  pull_request:

jobs:
  updater:
    name: 'Create PRs for nix dependencies'
    timeout-minutes: 5 # if this takes more than 5 minutes then something's wrong
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-21.11

    - name: nix cache warm up
      uses: cachix/cachix-action@v10
      with:
        name: ninegua
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Update sources.nix
      run: |
        nix-shell -p update-nix-fetchgit --run 'update-nix-fetchgit ./nix/sources.nix'
        git commit -a -m "Update sources.nix"

    - uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const execa = require('execa');
          const { head } = await execa('git', ['rev-parse', 'HEAD']);
          const result = await github.rest.pulls.create({
            title: 'Update source dependencies',
            owner,
            repo,
            head: head,
            base: 'main',
            body: [
              'This PR is auto-generated'
            ].join('\n')
          });
          github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: result.data.number,
            labels: ['autoupdate']
          });
