name: Update dependencies (weekly)
on:
  schedule:
    - cron:  '0 4 * * 1'
  pull_request:

jobs:
  updater:
    name: 'Create PRs for nix dependencies'
    timeout-minutes: 5 # if this takes more than 5 minutes then something's wrong
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    - name: Update sources.nix
      run: |
        nix-env -f '<nixpkgs>' -iA update-nix-fetchgit
        update-nix-fetchgit ./nix/sources.nix
        echo '${{ github.ref_name }}'
        BRANCH="autoupdate-$(date +%s)"
        git checkout -b $BRANCH
        git config user.email "autoupdate@github.actions"
        git config user.name "Auto Update"
        git commit -a -m "Update sources.nix"
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo '${{ github.ref_name }}'

    - name: Create PR
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "${{ env.BRANCH }}"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "feature, automated pr"
        pr_title: "Update source dependencies"
