name: Update niv dependencies (weekly)
on:
  schedule:
    - cron:  '0 4 * * 1'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    timeout-minutes: 2 # if this takes more than 2 minutes then something's wrong
    runs-on: ubuntu-latest
    steps:
      # notice there is no checkout step
      - name: niv-updater-action
        uses: knl/niv-updater-action@v10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
